### ISSUE TITLE
[OTHER] Connect With Me Icons - bad quality

### ISSUE THREAD

**Issue by KendallDoesCoding** [vikasganiga05/vikasganiga05#4]
### What would you like to share?

The connect with me icons are BAD quality, please shift them to better quality icons

### Additional information

![image](https://user-images.githubusercontent.com/84712013/181908566-e9838f52-6930-436d-b367-19ffa9a4dcc9.png)

**Comment by vikasganiga05** [comment]
Thanks for sharing the issue :pray:
